adding final task2 and script file
elnemesisdivina/Terraform_tasks pull request #4
Opened 2021-08-30 21:47 UTC by elnemesisdivina

2021-08-30 21:50 UTC, vladimirmukhin requested changes

2021-08-30 21:50 UTC, vladimirmukhin commented on main_improved.tf
> +*/
Commented-out code blocks isn't a good practice in turn of the quality of code. I suggest removing provisioner block completely

2021-08-30 21:50 UTC, vladimirmukhin commented on install_el_apache.sh
> +sudo systemctl enable apache2
Most likely it will fail. You don't need sudo. In the case of userdata, all commands are run as sudo by default.

2021-08-30 23:12 UTC, elnemesisdivina commented
> _No description provided._

address comments on last review

2021-08-31 00:28 UTC, vladimirmukhin approved these changes
Reamin main_improved.tf to main.tf and feel free to merge

2021-08-31 00:31 UTC, merged